package vidar.websystem.constants;

public class Pages {
    public static final String ADMIN_PERFUMES = "admin-perfumes";
    public static final String ADMIN_EDIT_PERFUME = "admin-edit-perfume";
    public static final String ADMIN_ADD_PERFUME = "admin-add-perfume";
    public static final String ADMIN_ALL_USERS = "admin-all-users";
    public static final String ADMIN_USER_DETAIL = "admin-user-detail";
    public static final String ORDER = "order";
    public static final String ORDERS = "orders";
    public static final String ORDERING = "ordering";
    public static final String ORDER_FINALIZE = "order-finalize";
    public static final String PRODUCT = "product";
    public static final String PRODUCTS = "products";
    public static final String USER_ACCOUNT = "user-account";
    public static final String USER_INFO = "user-info";
    public static final String USER_INFO_EDIT = "user-info-edit";
    public static final String USER_PASSWORD_RESET = "user-password-reset";
    public static final String FORGOT_PASSWORD = "forgot-password";
    public static final String RESET_PASSWORD = "reset-password";
    public static final String CONTACTS = "contacts";
    public static final String CART = "cart";
    public static final String HOME = "home";
    public static final String LOGIN = "login";
    public static final String PACKING = "packing";
    public static final String INVENTORY = "inventory";
    public static final String CREATE_ORDER = "create-order";
    public static final String SALES_ORDERING = "sales-ordering";
    public static final String SALES_ORDERS = "sales-orders";
    public static final String UPDATE = "update";
    public static final String UPDATE_INVENTORY = "update-inventory";
    public static final String ADD_NEW_CONTAINER = "add-new-container";
    public static final String UPDATE_CONTAINERS = "update-containers";
    public static final String UPDATE_ALL_PRODUCTS = "update-all-products";
    public static final String UPDATE_PRODUCT = "update-product";
    public static final String ADD_NEW_PRODUCT = "add-new-product";
    public static final String REGISTRATION = "registration";
    public static final String ERROR_404 = "error-404";
    public static final String ERROR_500 = "error-500";
}
