INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id) 
VALUES (1, 'Germany', null, '17d6f8a1-aa84-4823-bd18-ccb0fdbe7fe9.Hugo Boss Hugo Man.jpg', 'Moss, Sandalwood, Fir balsam', 'Carnation, Geranium leaf, Jasmine', 'Basil, Grapefruit, Green apple, Mint', 'male', 'Hugo Man', 'Hugo Boss', 21, 'Eau de Toilette', '75', 1995, 1);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id) 
VALUES (2, 'Germany', null, 'ba9272ca-20af-4e41-89b7-24018be4acb1.Hugo Boss The Scent.jpg', 'Leather', 'Maninka fruit, Lavender', 'Ginger', 'male', 'The Scent', 'Hugo Boss', 45, 'Eau de Toilette', '100', 2015, 1);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id) 
VALUES (3, 'Germany', null, '540f8e7d-2259-4a20-becf-4ed5cfc2912e.Hugo Boss Boss Woman.jpg', 'Sandalwood, Cedar', 'Freesia, Violet root', 'Mandarin orange, Mango', 'female', 'Boss Woman', 'Hugo Boss', 26, 'Eau de parfum', '90', 2000, 1);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id) 
VALUES (4, 'Germany', null, '1fb6dd1b-a134-4e6f-8215-60d465d33d72.Hugo Boss Hugo Deep Red.jpg', 'Musk, Sandalwood, Vanilla', 'Freesia, Hibiscus, Ginger', 'Pear, Blood orange, Clementine', 'female', 'Deep Red', 'Hugo Boss', 27, 'Eau de parfum', '90', 2001, 1);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id) 
VALUES (5, 'Germany', null, '62e9bf9b-8fea-4eb2-9935-21e868e1b93d.Hugo Boss The Scent For Her.jpg', 'Roasted cocoa', 'Osmanthus', 'Peach, Freesia', 'female', 'The Scent For Her', 'Hugo Boss', 47, 'Eau de parfum', '100', 2016, 1);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id) 
VALUES (6, 'Great Britain', null, '8297191e-ea2d-4f76-a1a0-004cc5beb127.Burberry London For Men.jpg', 'Oak bark, Gaiac wood, Opoponax', 'Leather, Mimosa, Port wine', 'Bergamot, Lavender, Black pepper', 'male', 'London For Men', 'Burberry', 27, 'Eau de Toilette', '100', 2006, 1);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id) 
VALUES (7, 'Great Britain', null, 'a5f18e03-340d-4e84-a7da-900683ecfe9f.Burberry Mr. Burberry.jpg', 'Sandalwood, Vetiver, Gaiac wood', 'Leather, Mimosa, Port wine', 'Grapefruit, Tarragon, Cardamom', 'male', 'Mr. Burberry', 'Burberry', 20, 'Eau de Toilette', '50', 2016, 1);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id) 
VALUES (8, 'Great Britain', null, '83a69c92-738a-4b49-a6de-1367050a8c01.Burberry The Beat For Men.jpg', 'Vetiver, Woody notes', 'Geranium, White thyme', 'Black pepper, Citron, Violet leaf', 'male', 'The Beat For Men', 'Burberry', 44, 'Eau de Toilette', '100', 2008, 1);