INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id, plank_color_id, wood_species_id, installation_pattern_id, grade_id, batch_id, cartons_per_skid) 
VALUES (1, 'Germany', null, '6ODFW387.jpg', 'Moss, Sandalwood, Fir balsam', 'Carnation, Geranium leaf, Jasmine', 'Basil, Grapefruit, Green apple, Mint', 'male', 'Hugo Man', 'Hugo Boss', 3.99, 'Eau de Toilette', '75', 1995, 1, 3, 1, 1, 1, '6O-NUT379', 54);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id, plank_color_id, wood_species_id, installation_pattern_id, grade_id, batch_id, cartons_per_skid) 
VALUES (2, 'Germany', null, '6OFTN349.jpg', 'Leather', 'Maninka fruit, Lavender', 'Ginger', 'male', 'The Scent', 'Hugo Boss', 4.99, 'Eau de Toilette', '100', 2015, 2, 4, 1, 1, 1, '7O-NAT86', 40);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id, plank_color_id, wood_species_id, installation_pattern_id, grade_id, batch_id, cartons_per_skid) 
VALUES (3, 'Germany', null, '6OLMK533.jpg', 'Sandalwood, Cedar', 'Freesia, Violet root', 'Mandarin orange, Mango', 'female', 'Boss Woman', 'Hugo Boss', 3.79, 'Eau de parfum', '90', 2000, 3, 5, 1, 1, 1, '7O-DFW442', 40);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id, plank_color_id, wood_species_id, installation_pattern_id, grade_id, batch_id, cartons_per_skid) 
VALUES (4, 'Germany', null, '6OSMG443.jpg', 'Musk, Sandalwood, Vanilla', 'Freesia, Hibiscus, Ginger', 'Pear, Blood orange, Clementine', 'female', 'Deep Red', 'Hugo Boss', 3.59, 'Eau de parfum', '90', 2001, 4, 6, 1, 1, 1, '8O-SMG443', 45);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id, plank_color_id, wood_species_id, installation_pattern_id, grade_id, batch_id, cartons_per_skid) 
VALUES (5, 'Germany', null, '6OMRN527.png', 'Roasted cocoa', 'Osmanthus', 'Peach, Freesia', 'female', 'The Scent For Her', 'Hugo Boss', 2.69, 'Eau de parfum', '100', 2016, 1, 1, 2, 1, 1, null, null);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id, plank_color_id, wood_species_id, installation_pattern_id, grade_id, batch_id, cartons_per_skid) 
VALUES (6, 'Great Britain', null, '6ODAS318.png', 'Oak bark, Gaiac wood, Opoponax', 'Leather, Mimosa, Port wine', 'Bergamot, Lavender, Black pepper', 'male', 'London For Men', 'Burberry', 3.49, 'Eau de Toilette', '100', 2006, 1, 2, 1, 1, 1, null, 48);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id, plank_color_id, wood_species_id, installation_pattern_id, grade_id, batch_id, cartons_per_skid) 
VALUES (7, 'Great Britain', null, '6OSST537.png', 'Sandalwood, Vetiver, Gaiac wood', 'Leather, Mimosa, Port wine', 'Grapefruit, Tarragon, Cardamom', 'male', 'Mr. Burberry', 'Burberry', 3.29, 'Eau de Toilette', '50', 2016, 1, 2, 1, 1, 1, null, 48);
INSERT INTO hardwoodfloors (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, plank_size_id, plank_color_id, wood_species_id, installation_pattern_id, grade_id, batch_id, cartons_per_skid) 
VALUES (8, 'Great Britain', null, '6OTOC676.png', 'Vetiver, Woody notes', 'Geranium, White thyme', 'Black pepper, Citron, Violet leaf', 'male', 'The Beat For Men', 'Burberry', 3.69, 'Eau de Toilette', '100', 2008, 1, 1, 1, 1, 1, null, 48);